# This file was generated by GoReleaser. DO NOT EDIT.
cask "tpq" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "23da8d5e9a1cb9fc89f92cf1facaeb3104a8247e378bfe24b2d83cdece4816f0"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac405ad19138b07390435967459e8325ebf1b45feeb8b648e238dc0a20fb4b32"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2d09ac6db82a7dcf6387f2b63aefba2b81abb30119b43e9cb7976de03e1197a9"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e8b592de00a7985117a07f298b71216e55effe7ca8b95057ac853d715938889"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tpq"
  desc "CLI for querying the Terraform registry for provider versions."
  homepage "https://github.com/mattias-fjellstrom/terraform-provider-query"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tpq"

  # No zap stanza required

end
