# This file was generated by GoReleaser. DO NOT EDIT.
cask "tpq" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "153802fda784a1f6a4aa880db72b10bfa9d79e2e5c07372968a981163e8da7a0"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "66f6cb0e9f9107276fd6735c79b1d08fde504d208a6edfe5cdbc4e0a13d9efe2"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f16ad6e73515d06c7a03d95bbef5c32ee8c5030eeaec86163599820e89b0186b"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8cc066fa31998976edee19d794854bdd05afa80c71445fa55a617df55e7d257b"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tpq"
  desc "Interactive TUI for browsing the Terraform registry."
  homepage "https://github.com/mattias-fjellstrom/terraform-provider-query"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tpq"

  # No zap stanza required

end
