# This file was generated by GoReleaser. DO NOT EDIT.
cask "tpq" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ddc419c19d2a437f13866efd986801d35311a17b66e8ec278f8e210bf969e05e"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "98951e1916a151020a73ae55605b82159bc9b417f8e68faf017a8b4ddc02573e"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66c0574f8fc66852e37af8a3170c38a985173420eaa78c0f0814214f5b2f15c4"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "10e86e4238b07451bb51ef026286cad862dac7c01b6a019b720548e28ec14e8c"
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v#{version}/terraform-provider-query_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tpq"
  desc "Interactive TUI for browsing the Terraform registry."
  homepage "https://github.com/mattias-fjellstrom/terraform-provider-query"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tpq"

  # No zap stanza required

end
