# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tpq < Formula
  desc "CLI for querying the Terraform registry for provider versions."
  homepage "https://github.com/mattias-fjellstrom/terraform-provider-query"
  version "0.1.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v0.1.0/terraform-provider-query_0.1.0_darwin_amd64.tar.gz"
      sha256 "3cb6150dd191fc8576590c91f88ab65ce1ffba1f0f5225564e03a63b095d16ec"

      define_method(:install) do
        bin.install "tpq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v0.1.0/terraform-provider-query_0.1.0_darwin_arm64.tar.gz"
      sha256 "4a0ebb6baf67b99aafe334107258c9e02b8c1699d61101438abc665f8e69db48"

      define_method(:install) do
        bin.install "tpq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v0.1.0/terraform-provider-query_0.1.0_linux_amd64.tar.gz"
      sha256 "76719367a70fefa2b72354125f14378e0d444ad48b3658c6223750e3067ed9b0"
      define_method(:install) do
        bin.install "tpq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattias-fjellstrom/terraform-provider-query/releases/download/v0.1.0/terraform-provider-query_0.1.0_linux_arm64.tar.gz"
      sha256 "971ae89ed3cca3c3ff31df2a123958c2d3c6f13214d051aa9e704076912a151b"
      define_method(:install) do
        bin.install "tpq"
      end
    end
  end

  test do
    system "#{bin}/tpq", "--help"
  end
end
